<!-- teste promise -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>

    <script>


        function a(falhar) {

            return new Promise((resolve, reject) => {

                setTimeout(() => {

                    if (falhar) {

                        reject('PROMISE A FALHOU');
                    } else {

                        console.log('PROMISE A RESOLVIDA');
                        resolve('DADO A');
                    }

                }, 2000);
            });
        }

        function b(falhar) {

            return new Promise((resolve, reject) => {

                setTimeout(() => {

                    if (falhar) {

                        reject('PROMISE B FALHOU');
                    } else {

                        console.log('PROMISE B RESOLVIDA')
                        resolve('DADO B');
                    }

                }, 1000);
            });
        }

        function c(falhar) {

            return new Promise((resolve, reject) => {

                setTimeout(() => {

                    if (falhar) {

                        reject('PROMISE C FALHOU');
                    } else {

                        console.log('PROMISE C RESOLVIDA')
                        resolve('DADO C');
                    }

                }, 500);
            });
        }

        // As promisses são executadas de maneira ordenada como está organizado abaixo, no caso, é excutado primeiro a função a(), depois b(), 
        // e então c(), onde caso ocorra um reject em uma das execuções, ocorrerá o impedimento da execução da proxima promisse

        // Diferente da promisse All, onde as promisses são executadas em paralelo, caso recomendado caso não haja dependência entre as promisses

        // teste, fazendo a promise c ser rejeitada

        a()
            .then(dado => {
                console.log(dado);
                // O RETORNO DA PROMISE B ESTARÁ DISPONÍVEL NO PRÓXIMO THEN
                return b();
            })
            .then(dado => {
                console.log(dado);

                /* FORÇANDO A REJEIÇÃO DA PROMISE. TEM QUE IR DIRETO PARA O CATCH. 
                SE NÃO TIVESSE REJEITADO, O RETORNO DE C ESTARIA DISPONÍVEL NO PRÓXIMO THEN */
                return c(true);
            })
            .then(dado => {
                console.log(dado);
            })
            .catch(erro => console.log(erro));

            // as promisses são executadas ao mesmo tempo e o retorno da Promisse All é um array com o resultado das promisses
        Promise
            .all([a(), b(), c()])
            .then(arrayComResultadoDasPromises => console.log(arrayComResultadoDasPromises))
            .catch(erroDeAlgumaDasPromises => console.log(erroDeAlgumaDasPromises));

    </script>
</body>